/**
 * app/api/enroll/route.ts
 *
 * POST /api/enroll
 * Body: { personId: number, descriptor: number[] }
 *
 * PURPOSE:
 * Saves the 128-float face descriptor generated by face-api.js in the browser
 * into the person's row in MSSQL.
 *
 * This only needs to happen ONCE per person (or when re-enrolling).
 * After enrollment, the person's face can be recognized by the scanner.
 *
 * FLOW:
 *   Admin opens enrollment page
 *     → selects a person from the database
 *     → looks into the camera
 *     → face-api.js generates a 128-float descriptor in the browser
 *     → browser POSTs { personId, descriptor } to this route
 *     → we serialize descriptor to JSON and UPDATE the row in MSSQL
 *     → person is now enrollable
 *
 * SECURITY NOTE:
 * In production, protect this route with authentication middleware
 * so only admins can enroll faces. Example: check a session token or
 * use next-auth's getServerSession().
 */

import sql from "mssql";
import { type NextRequest, NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import type { EnrollRequestBody } from "@/types";

export async function POST(req: NextRequest) {
  try {
    const body: EnrollRequestBody = await req.json();
    const { personId, descriptor } = body;

    // Basic validation
    if (!personId || !descriptor || descriptor.length !== 128) {
      return NextResponse.json(
        { error: "personId and a 128-element descriptor array are required" },
        { status: 400 },
      );
    }

    const db = await getDb();

    // Serialize the float array to a JSON string for NVARCHAR(MAX) storage
    const descriptorJson = JSON.stringify(descriptor);

    const result = await db
      .request()
      .input("id", sql.Int, personId)
      .input("descriptor", sql.NVarChar(sql.MAX), descriptorJson)
      .query(`
        UPDATE people
        SET face_descriptor = @descriptor
        WHERE id = @id
      `);

    // rowsAffected[0] tells us if the UPDATE actually matched a row
    if (result.rowsAffected[0] === 0) {
      return NextResponse.json(
        { error: `No person found with id ${personId}` },
        { status: 404 },
      );
    }

    return NextResponse.json({ success: true, personId });
  } catch (error) {
    console.error("POST /api/enroll error:", error);
    return NextResponse.json(
      { error: "Failed to save descriptor" },
      { status: 500 },
    );
  }
}
